version: '3'

networks:
  gira-network:
    driver: bridge

services:
  front-end:
    build:
      context: ..
      # TODO: remove this
      dockerfile: ./docker/Dockerfile.front-end
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - gira-network
    environment:
      - GIRA_PORT=4000
      - GIRA_API_ADDRESS=http://api:4001
      - GIRA_SESSION_SECRET="sessi0nsecR3t"
      - GIRA_ENFORCE_HTTPS=false
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    expose:
      - "4001"
    networks:
      - gira-network
    environment:
      - GIRA_PORT=4001
      - GIRA_DB_HOST=postgres
      - GIRA_DB_PORT=5432
      - GIRA_DB_USER=gira
      - GIRA_DB_PASSWORD=password
      - GIRA_DB_NAME=gira
      - GIRA_SECRET="sessi0nsecRE7"
      - GIRA_USE_SSL=false
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=gira
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    restart: on-failure
    networks:
      - gira-network
