FROM golang:alpine AS builder

RUN mkdir /app

ADD . /app/

WORKDIR /app

RUN go build -o front-end ./cmd/front-end

FROM alpine:latest

COPY --from=builder /app/front-end .

ENV PORT ""
ENV BACK_END_ADDR ""
ENV SESSION_SECRET ""

CMD ./front-end -port=${PORT} -api_addr=${BACK_END_ADDR} -session_secret=${SESSION_SECRET}
