FROM golang:alpine AS builder

RUN mkdir /app

ADD . /app/

WORKDIR /app

RUN go build -o front-end ./cmd/front-end

FROM gcr.io/distroless/static-debian11:latest

COPY --from=builder /app/front-end .
COPY --from=builder /app/ui ./ui

ENTRYPOINT [ "./front-end" ]
