FROM golang:alpine AS builder

RUN mkdir /app

ADD . /app/

WORKDIR /app

RUN go build -o api ./cmd/api

FROM gcr.io/distroless/static-debian11:latest

COPY --from=builder /app/api .

ENTRYPOINT [ "./api" ]
