FROM golang:alpine AS builder

RUN mkdir /app

ADD . /app/

WORKDIR /app

RUN go build -o front-end ./cmd/front-end

FROM alpine:latest

COPY --from=builder /app/front-end .
COPY --from=builder /app/ui ./ui

CMD ./front-end
