// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gira-games/api/cmd/api/server (interfaces: GameModel)

// Package fixtures is a generated GoMock package.
package fixtures

import (
	models "github.com/gira-games/api/pkg/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// GameModelMock is a mock of GameModel interface
type GameModelMock struct {
	ctrl     *gomock.Controller
	recorder *GameModelMockMockRecorder
}

// GameModelMockMockRecorder is the mock recorder for GameModelMock
type GameModelMockMockRecorder struct {
	mock *GameModelMock
}

// NewGameModelMock creates a new mock instance
func NewGameModelMock(ctrl *gomock.Controller) *GameModelMock {
	mock := &GameModelMock{ctrl: ctrl}
	mock.recorder = &GameModelMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *GameModelMock) EXPECT() *GameModelMockMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *GameModelMock) All() ([]*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].([]*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All
func (mr *GameModelMockMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*GameModelMock)(nil).All))
}

// AllForUser mocks base method
func (m *GameModelMock) AllForUser(arg0 string) ([]*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllForUser", arg0)
	ret0, _ := ret[0].([]*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllForUser indicates an expected call of AllForUser
func (mr *GameModelMockMockRecorder) AllForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllForUser", reflect.TypeOf((*GameModelMock)(nil).AllForUser), arg0)
}

// Get mocks base method
func (m *GameModelMock) Get(arg0 string) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *GameModelMockMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*GameModelMock)(nil).Get), arg0)
}

// Insert mocks base method
func (m *GameModelMock) Insert(arg0 *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *GameModelMockMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*GameModelMock)(nil).Insert), arg0)
}
