version: '3'

networks:
  integration-tests-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    ports:
      - '21665:5432'
    environment:
      - POSTGRES_USER=gira
      - POSTGRES_PASSWORD=password
    expose:
      - "21665"
    restart: on-failure
    networks:
      - integration-tests-network
