-- +goose Up
CREATE TABLE FRANCHISES (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE GAMES (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  franchise_id INTEGER REFERENCES FRANCHISES(id)
);

CREATE TABLE USERS (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  hashed_password CHAR(60) NOT NULL
);

CREATE TABLE USER_GAMES (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES USERS(id),
  game_id INTEGER REFERENCES GAMES(id),
  status VARCHAR(255) DEFAULT 'To Do',
  current_progress INTEGER DEFAULT 0,
  final_progress INTEGER DEFAULT 100
);

CREATE TABLE USER_TOKENS (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES USERS(id),
  token VARCHAR(400)
);

ALTER TABLE users ADD CONSTRAINT users_uc_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT users_uc_username UNIQUE (username);

ALTER TABLE user_games ADD CONSTRAINT user_games_unique_user_game UNIQUE (user_id, game_id);

-- +goose Down
DROP TABLE USER_TOKENS;
DROP TABLE USER_GAMES;
DROP TYPE GAME_STATUS;
DROP TABLE USERS;
DROP TABLE GAMES;
DROP TABLE FRANCHISES;

