name: Build
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  api:
    name: Build Gira ${{ matrix.service }} with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20"]
        service: ['api', 'front-end']

    steps:
    - uses: actions/checkout@v1
    - name: Set go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build Gira API service
      run: |
        go build ./cmd/${{ matrix.service }}
