name: Integration tests
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Run the integrations tests with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15, 1.14]

    steps:
    - uses: actions/checkout@v1
    - name: Set go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run the tests with Go ${{ matrix.go-version }}
      run: |
        make integration_tests
