name: Lint
on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  api:
    name: Lint project with golangci-lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
