name: Test
on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  api:
    name: Run the tests of the project with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14, 1.13]

    steps:
    - uses: actions/checkout@v1
    - name: Set go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run the tests with Go ${{ matrix.go-version }}
      run: |
        go test ./...
